# Path to your oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"
export PATH="/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/2.6.0/bin:$PATH"
export EDITOR="nvim"

ZSH_THEME="spaceship"

SPACESHIP_DOCKER_SHOW=false
SPACESHIP_KUBECONTEXT_SHOW=false
SPACESHIP_CHAR_SYMBOL="λ " SPACESHIP_GIT_SYMBOL="\ue702 "
SPACESHIP_GIT_BRANCH_COLOR="red"
SPACESHIP_ELIXIR_SYMBOL="\ue62d "

plugins=(
  git
  docker
  tmuxinator
  mix
) source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

autoload -U promptinit; promptinit
prompt spaceship

alias ref='source ~/.zshrc'

alias v="nvim"
alias aqua="Asciiquarium"

# Tmux
alias tn='tmux new -s'
alias tk='tmux kill-session -t'
alias tl='tmux ls'
alias taa='tmux attach -t'
alias tx='tmuxinator'
alias txc='tmuxinator copy'

# AWS
alias aws-personal='export AWS_DEFAULT_PROFILE=personal'
alias aws-digitalprofile='export AWS_DEFAULT_PROFILE=digitalprofile'
alias aws-default='export AWS_DEFAULT_PROFILE=default'

# Task warrior tooling
alias ta="task"
alias tap="task context personal"
alias taw="task context work"
alias in='task add +in'
alias d='delta'

alias tw='timew'

delta() {
  if [ "$1" = "launch" ]; then
    tmuxinator start $2
  fi
  
  if [ "$1" = "l" ]; then
    tmuxinator start $2
  fi

  echo "Incorrect usage of delta"
}

notes() {
  tmuxinator start notes
}

# chunkwm
alias chunkr='brew services restart chunkwm'
alias chunks='brew services start chunkwm'
alias chunkst='brew services stop chunkwm'

# Docker
alias drm='docker rm $(docker ps -aq) --force'

# Git
alias gs='git status'

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
eval "$(direnv hook zsh)"
